APP_NAME = "FaceMouse AI"
WINDOW_SIZE = "500x420"
THEME_MODE = "dark"
COLOR_THEME = "blue"

SENSITIVITY = 1.8
SMOOTHING = 7
DEAD_ZONE = 0.015

CAMERA_INDEX = 0
BLINK_THRESHOLD = 0.015
RIGHT_CLICK_HOLD_FRAMES = 12